name: Deploy Bitmovin Player UI Demo to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Gulp CLI
      run: npm install -g gulp-cli
      
    - name: Build project
      run: gulp
      
    - name: Prepare GitHub Pages content
      run: |
        # Create docs directory for GitHub Pages
        mkdir -p docs
        
        # Copy the demo HTML files
        cp src/html/index.html docs/
        cp src/html/simple.html docs/
        
        # Copy built CSS and JS files
        cp -r dist/css docs/
        cp -r dist/js docs/
        
        # Copy assets (images, etc.)
        cp -r assets docs/
        
        # Create a simple index redirect if needed
        echo "Demo ready at index.html" > docs/README.md
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4